<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>__TargetFramework__</TargetFramework>
    <RootNamespace>__ProjectName__.Tests</RootNamespace>
    <AssemblyName>__ProjectName__.Tests</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>

    <!-- xUnit v3 roda o projeto de teste como executável. -->
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.0" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\__ProjectName__\__ProjectName__.csproj" />
  </ItemGroup>

</Project>
